# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**\dep\build\.nuget\packages.json'
  buildPlatform: 'x86|x64|ARM64'
  buildConfiguration: 'Release'
  NuGetCommand: '-PackagesDirectory d:\a\'


steps:
- task: NuGetToolInstaller@0
  
- task: NuGetCommand@2
  inputs:
    command: 'custom'
    feedsToUse: 'select'
    includeNuGetOrg: false
    versioningScheme: 'off'
    arguments: 'restore d:\a\1\s\build\.nuget\packages.config -PackagesDirectory d:\a\1\s/packages -Verbosity Detailed -NonInteractive -ConfigFile d:\a\1\s\build\config\NuGet.config'


- task: VSBuild@1
  inputs:
    platform: 'x64'
    solution: '**\OpenConsole.sln'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'
